import { Raleway } from 'next/font/google'
import './global.css';

const inter = Raleway({ 
  weight: ['400', '800'],
  subsets: ['latin'],
  style: ['normal', 'italic']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
